# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-lock.txt -r requirements.txt
        # This should detect if the locked requirements are stale
    - name: Lint with flake8
      run: |
        python -m flake8
    - name: Test with pytest
      run: |
        python -m pytest day*/*
    - name: Test with mypy
      run: |
        python -m mypy day*/
